services:
  postgres:
    image: postgres:17.4
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  restapi:
    build: ./rest
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
    develop:
      watch:
        - action: sync+restart
          path: ./rest
          target: /code/rest
  media:
    build: ./media
    ports:
      - "8080:8000"
    volumes:
      - ./images:/var/lib/media/images
    develop:
      watch:
        - action: sync+restart
          path: ./media
          target: /code/media
volumes:
  keymech-data:
